on:
  workflow_dispatch:
  push:
    branches:
    - main

steps:
  - uses: actions/checkout@v4
  - uses: toitlang/action-setup@v1
  - run: 
    - toit.compile -w komodo.snapshot src/toit/src/komodo.toit
    - firmware -e firmware-esp32s3.envelope container install komodo komodo.snapshot

            
