name: "Micropython Firmware Generator (RP2)"
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  make:
    name: "Firmware Generation"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
      
    - uses: actions/checkout@master
      with:
        repository: micropython/micropython
        ref: v1.20.0
        submodules: true
        path: micropython
        
    - name: Install packages
      run: |
        source micropython/tools/ci.sh && ci_rp2_setup
        
    - name: Copy board
      run: |
        mkdir micropython/ports/rp2/boards/REPTRAP
        cp -a src/micropython/board/REPTRAP/. micropython/ports/rp2/boards/REPTRAP
      
    - name: Copy project files
      run: |
        mkdir micropython/ports/rp2/boards/modules/
        cp src/micropython/app.py micropython/ports/rp2/boards/modules/
        cp src/micropython/config.py micropython/ports/rp2/boards/modules/
        cp src/micropython/constants.py micropython/ports/rp2/boards/modules/
        cp src/micropython/lowpower.py micropython/ports/rp2/boards/modules/
        cp src/micropython/sensorcfg.py micropython/ports/rp2/boards/modules/
        cp src/micropython/statistics.py micropython/ports/rp2/boards/modules/
        cp src/micropython/vl53l4cd.py micropython/ports/rp2/boards/modules/
        cp src/micropython/vl53l4cd_driver.py micropython/ports/rp2/boards/modules/
        cp src/micropython/main.py micropython/ports/rp2/boards/modules/
        
    - name: Build Micropython
      run: |
        cd micropython
        make ${MAKEOPTS} -C mpy-cross
        make ${MAKEOPTS} -C ports/rp2 submodules
        make ${MAKEOPTS} -C ports/rp2
        make ${MAKEOPTS} -C ports/rp2 BOARD=PICO
        
    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: RepTrap-Firmware
        path: |
          micropython/ports/rp2/build-PICO/firmware.hex
          micropython/ports/rp2/build-PICO/firmware.uf2
          micropython/ports/rp2/build-PICO/firmware.bin
