name: "Toit Firmware Generation"
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOIT_VERSION: "v2.0.0-alpha.145"
      ENVELOPE_FILE: "firmware-esp32s3"
      FIRMWARE_FILE: "heimdall-esp32s3"
    steps:
      - uses: actions/checkout@v4
      - uses: toitlang/action-setup@v1
        with:
          toit-version: ${{ env.TOIT_VERSION }}
      - name: Download and unpack envelope
        working-directory: src/toit
        run: |
          wget https://github.com/toitlang/envelopes/releases/download/${{ env.TOIT_VERSION }}/${{ env.ENVELOPE_FILE }}.envelope.gz
          gunzip ${{ env.ENVELOPE_FILE }}.envelope.gz
      - name: Build toit firmware
        working-directory: src/toit
        run: |
          toit.pkg install
          toit.compile -w komodo.snapshot src/komodo.toit
          ${{env.TOIT_INSTALL_DIR}}/toit/tools/firmware -e ${{ env.ENVELOPE_FILE }}.envelope container install komodo komodo.snapshot
          ${{env.TOIT_INSTALL_DIR}}/toit/tools/firmware extract -e ${{ env.ENVELOPE_FILE }}.envelope -o ${{env.FIRMWARE_FILE}}.bin
      - name: Upload envelope
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.FIRMWARE_FILE}}.bin
          path: src/toit/${{env.FIRMWARE_FILE}}.bin

      - name: Get release
        id: get_release
        uses: actions/github-script@v5
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', '')
            });
            return release.data.upload_url;
        if: github.event_name == 'release'

      - name: Upload firmware to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.result }}
          asset_path: src/toit/${{ env.FIRMWARE_FILE }}.bin
          asset_name: ${{ env.FIRMWARE_FILE }}.bin
          asset_content_type: application/octet-stream
        if: github.event_name == 'release'